version: "3.7"

services:
  server:
    image: node:16.9.0-alpine
    command: sh -c "npm install && node ."
    restart: unless-stopped
    depends_on:
      - "mysql"
    working_dir: /app
    volumes:
      - ./:/app
  mysql:
      image: mysql:8.0
      ports:
        - 3306:3306
      volumes:
        - bandbot-db:/var/lib/mysql
        - ./db:/tmp/db
      environment: 
        MYSQL_ROOT_PASSWORD: ${DB_ROOTPW}
        MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  bandbot-db: